### ISSUE TITLE
QML module not found (MeuiKit)

### ISSUE THREAD

**Issue by Z-bin** [cyberos/cyber-fm#1]
**Development environment**: Ubuntu 20.04
I have installed [meuikit,](https://github.com/cyberos/meuikit) but still report error: "QML module not found (MeuiKit)".How can I solve this problem?
**the error:**
![image](https://user-images.githubusercontent.com/22768973/102707495-74815680-42d6-11eb-989f-5a3fa0443be8.png)
**installed:MeuiKit**
![image](https://user-images.githubusercontent.com/22768973/102707518-a5fa2200-42d6-11eb-9b00-c5df60b9f518.png)

**Comment by reionwong** [comment]
Oh, this is our mistake, we are developing under the ARCHLINUX development ENV. MeuiKit's CMake file does not recognize the Qt's lib directory, so the Qt lib installation directory is different in other linux environments.

You can refer to the 'qml-module-qtquick-controls' package of ubuntu: https://packages.ubuntu.com/groovy/amd64/qml-module-qtquick-controls/filelist

```
/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ApplicationWindow.qml
/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ApplicationWindow.qmlc
/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/BusyIndicator.qml
/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/BusyIndicator.qmlc
/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml
/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qmlc
/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Calendar.qml
```
So you need to modify the `INSTALL_QMLDIR` variable of Meuikit's `CMakeLists.txt`:

```
set(INSTALL_QMLDIR /usr/lib/x86_64-linux-gnu/qt5/qml/)
```

Try it :)

**Comment by Z-bin** [comment]
> Oh, this is our mistake, we are developing under the ARCHLINUX development ENV. MeuiKit's CMake file does not recognize the Qt's lib directory, so the Qt lib installation directory is different in other linux environments.
> 
> You can refer to the 'qml-module-qtquick-controls' package of ubuntu: https://packages.ubuntu.com/groovy/amd64/qml-module-qtquick-controls/filelist
> 
> ```
> /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ApplicationWindow.qml
> /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/ApplicationWindow.qmlc
> /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/BusyIndicator.qml
> /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/BusyIndicator.qmlc
> /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qml
> /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Button.qmlc
> /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Calendar.qml
> ```
> 
> So you need to modify the `INSTALL_QMLDIR` variable of Meuikit's `CMakeLists.txt`:
> 
> ```
> set(INSTALL_QMLDIR /usr/lib/x86_64-linux-gnu/qt5/qml/)
> ```
> 
> Try it :)

Thank you so much for your enthusiastic answer, it worked.
Cyber is a great project, I will do my best to contribute code:)
