### ISSUE TITLE
Context menu is clipped to the window bounds

### ISSUE THREAD

**Issue by omaemae** [cyberos/cyber-fm#6]
![image](https://user-images.githubusercontent.com/17727163/102073616-d851de00-3e03-11eb-90fe-a2d9d3770505.png)
Any ways to fix this?

**Comment by rekols** [comment]
I am trying to fix it

**Comment by omaemae** [comment]
I'll test it right now.

**Comment by omaemae** [comment]
Yup, works fine. Closing.
